import json
import shutil
from pathlib import Path
from textwrap import dedent

from src.models.schemas import ProjectPlan


def _write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def _backend_main(plan: ProjectPlan) -> str:
    return dedent(
        f'''
        from fastapi import FastAPI

        app = FastAPI(
            title="{plan.project_name}",
            description="{plan.summary}",
            version="0.1.0",
        )


        @app.get("/")
        def root() -> dict[str, str]:
            return {{
                "message": "Welcome to {plan.project_name}",
                "status": "running",
            }}


        @app.get("/health")
        def health() -> dict[str, str]:
            return {{"status": "healthy"}}
        '''
    )


def _frontend_app(plan: ProjectPlan) -> str:
    feature_data = json.dumps(plan.features, indent=2)

    return dedent(
    	f'''
    	import React from "react";

    	const features = {feature_data};

        function App() {{
          return (
            <main>
              <h1>{plan.project_name}</h1>
              <p>{plan.summary}</p>

              <h2>Planned features</h2>
              <ul>
                {{features.map((feature) => (
                  <li key={{feature}}>{{feature}}</li>
                ))}}
              </ul>
            </main>
          );
        }}

        export default App;
        '''
    )


def _readme(plan: ProjectPlan) -> str:
    features = "\n".join(
        f"- {feature}" for feature in plan.features
    )

    warnings = (
        "\n".join(
            f"- {warning}" for warning in plan.warnings
        )
        or "- No warnings detected."
    )

    return dedent(
        f'''
        # {plan.project_name}

        Generated by AgentForge Studio.

        ## Description

        {plan.summary}

        ## Technology stack

        - Frontend: {plan.frontend}
        - Backend: {plan.backend}
        - Database: {plan.database}
        - Application type: {plan.application_type}

        ## Planned features

        {features}

        ## Security notes

        {warnings}

        ## Run the backend

        ```bash
        cd backend
        pip install -r requirements.txt
        uvicorn app.main:app --reload
        ```

        ## Run the frontend

        ```bash
        cd frontend
        npm install
        npm run dev
        ```
        '''
    )


def generate_project(
    plan: ProjectPlan,
    output_root: Path | str = "generated_projects",
    overwrite: bool = False,
) -> Path:
    output_root = Path(output_root)
    project_directory = output_root / plan.project_name

    if project_directory.exists():
        if not overwrite:
            raise FileExistsError(
                f"Project already exists: {project_directory}. "
                "Use --force to replace it."
            )

        shutil.rmtree(project_directory)

    project_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    _write_file(
        project_directory / "project_plan.json",
        json.dumps(
            plan.to_dict(),
            indent=2,
        ),
    )

    _write_file(
        project_directory / "manifest.json",
        json.dumps(
            {
                "generator": "AgentForge Studio",
                "version": "0.1.0",
                "project_name": plan.project_name,
                "frontend": plan.frontend,
                "backend": plan.backend,
                "database": plan.database,
            },
            indent=2,
        ),
    )

    _write_file(
        project_directory / "README.md",
        _readme(plan),
    )

    _write_file(
        project_directory
        / "backend"
        / "app"
        / "__init__.py",
        "",
    )

    _write_file(
        project_directory
        / "backend"
        / "app"
        / "main.py",
        _backend_main(plan),
    )

    _write_file(
        project_directory
        / "backend"
        / "requirements.txt",
        "fastapi>=0.115.0\n"
        "uvicorn[standard]>=0.30.0",
    )

    _write_file(
        project_directory
        / "backend"
        / ".env.example",
        f"APP_NAME={plan.project_name}\n"
        "DATABASE_URL=sqlite:///./app.db",
    )

    _write_file(
        project_directory
        / "frontend"
        / "package.json",
        json.dumps(
            {
                "name": f"{plan.project_name}-frontend",
                "private": True,
                "version": "0.1.0",
                "type": "module",
                "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                },
                "dependencies": {
                    "react": "^18.3.0",
                    "react-dom": "^18.3.0",
                },
                "devDependencies": {
                    "vite": "^5.4.0",
                },
            },
            indent=2,
        ),
    )

    _write_file(
        project_directory
        / "frontend"
        / "index.html",
        dedent(
            '''
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1.0"
                />
                <title>AgentForge Application</title>
              </head>
              <body>
                <div id="root"></div>
                <script
                  type="module"
                  src="/src/main.jsx"
                ></script>
              </body>
            </html>
            '''
        ),
    )

    _write_file(
        project_directory
        / "frontend"
        / "src"
        / "main.jsx",
        dedent(
            '''
            import React from "react";
            import ReactDOM from "react-dom/client";
            import App from "./App.jsx";

            ReactDOM.createRoot(
              document.getElementById("root")
            ).render(
              <React.StrictMode>
                <App />
              </React.StrictMode>
            );
            '''
        ),
    )

    _write_file(
        project_directory
        / "frontend"
        / "src"
        / "App.jsx",
        _frontend_app(plan),
    )

    _write_file(
        project_directory / ".gitignore",
        dedent(
            '''
            .env
            *.db
            *.sqlite
            *.sqlite3
            __pycache__/
            *.py[cod]
            node_modules/
            dist/
            '''
        ),
    )

    return project_directory